const K = {
  CATEGORIA: {
    CAT_01: 'ACCESORIOS',
    CAT_02: 'ALIMENTOS',
    CAT_03: 'CUIDADO_HIGIENE'
  },
  GRUPOS: {
    GRP_01: 'PERROS',
    GRP_02: 'GATOS'
  },
  MARCAS: {
    MRC_01: 'RICOCAN',
    MRC_02: 'RICOCAT',
    MRC_03: 'CANBO_DOG',
    MRC_04: 'CANBO_CAT',
    MRC_05: 'PET_CARE',
    MRC_06: 'DOG_CHOW',
    MRC_07: 'PRO_PLAN',
    MRC_08: 'NUTRAM',
    MRC_09: 'MIMASKOT',
    MRC_10: 'CAT_CHOW',
  },
  PRODUCTOS: {
    PRD_01: 'bebedero',
    PRD_02: 'cama de gato',
    PRD_03: 'casa de gato',
    PRD_04: 'dispensador de agua',
    PRD_05: 'Jaula para gatos',
    PRD_06: 'Juguete de gato	',
    PRD_07: 'Mochila para gato',
    PRD_08: 'Plato grande',
    PRD_09: 'Rascador_01',
    PRD_10: 'Rascador_02',
    PRD_11: 'Collar cuero',
    PRD_12: 'Collar puas',
    PRD_13: 'Dispensador de comida',
    PRD_14: 'Peine',
    PRD_15: 'Plato',
    PRD_16: 'Plato rosado',
    PRD_17: 'Rastrillo',
    PRD_18: 'Transporte para perro_01',
    PRD_19: 'Transporte para perro_02',
    PRD_20: 'cat_show',
    PRD_21: 'cat_show-pollo',
    PRD_22: 'felix-salmon',
    PRD_23: 'friskies-adulto',
    PRD_24: 'friskies-especial',
    PRD_25: 'ricocat',
    PRD_26: 'Pedigree',
    PRD_27: 'Ricocan',
    PRD_28: 'Thor',
    PRD_29: 'Arena para gatos',
    PRD_30: 'Arena para gatos premium',
    PRD_31: 'Eliminador de olores',
    PRD_32: 'Enjuague dental',
    PRD_33: 'Jabon dermatologico',
    PRD_34: 'Jabon-gatos',
    PRD_35: 'Talco desodorante-gatos',
    PRD_36: 'Cepillo de madera',
    PRD_37: 'Cepillo de plastico',
    PRD_38: 'Jabon-perro',
    PRD_39: 'Jabon_desodorante-perro',
    PRD_40: 'Perfume-perro',
    PRD_41: 'Perfume-perro_hembra',
    PRD_42: 'Perfume-perro_hembra',
    PRD_43: 'Spray oral',
    PRD_44: 'Talco',
  }
}
module.exports = K
